### ISSUE TITLE
Low quality audio

### ISSUE THREAD

**Issue by lumen-novum** [DrewThomasson/ebook2audiobookEspeak#1]
This works perfectly in a docker container but I have one question. Is it possible to increase the audio quality even if it requires more system resources?

The American voice sounds terrible and I would like to get the quality to be at least okay. I understand the intent may have been to use a lightweight model but it would be really nice to have the option to use something more accurate.

**Comment by DrewThomasson** [comment]
## Yes actually,


I have many different variations of this applications in my repo list all ending in the model they use



This one here uses e-speak which is crazy fast but sounds terrible 


## If you want speedy generation but good quality, try using my piper-tts variation of this which also has a docker image,

https://github.com/DrewThomasson/ebook2audiobookpiper-tts

There should be a demo file in that GitHub for you to hear



## I also have other similarly named GitHub repos that use other better tts engines:
Espeak : bad, super fast
Piper-tts : good, speedy
Styletts2 : great, slow
XTTS : BEST, slowest

**Comment by lumen-novum** [comment]
I will check out your other models, thank you for the suggestion!
